Hypothesis: {bottled beer} --> {rolls}, cookout
Minimum Support: 0.028
Minimum Lift: 1

In [14]:


import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import warnings

# suppresses pandas warnings
warnings.filterwarnings(
    "ignore",
    message=r"datetime\.datetime\.utcnow\(\) is deprecated",
    category=DeprecationWarning
)

import pandas as pd

In [15]:
df1 = pd.read_csv('grocerybasket.csv')
df1.head()

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df1.drop(columns=[df1.columns[0]],inplace=True)
market_basket = (
    pd.get_dummies(df1.stack())      # Flattens the df and creates one-hot columns for each item
    .groupby(level=0)               # Groups back by the original row index
    .max()                          # Keeps a 1 if the item was in that row, 0 otherwise
    .reindex(df1.index, fill_value=0) # Ensures rows that were completely empty are kept as 0
)
market_basket.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [17]:
# call apriori function and pass minimum support here  - this determines the number of times in total number of transaction that item was present.
frequent_itemsets = apriori(market_basket, min_support=0.028, use_colnames=True)
# it will generate frequent itemsets using two step approach
frequent_itemsets

     support                                     itemsets
0   0.033452                        frozenset({UHT-milk})
1   0.052466                            frozenset({beef})
2   0.033249                         frozenset({berries})
3   0.080529                    frozenset({bottled beer})
4   0.110524                   frozenset({bottled water})
..       ...                                          ...
68  0.040061                frozenset({soda, whole milk})
69  0.042298      frozenset({whole milk, tropical fruit})
70  0.029283          frozenset({yogurt, tropical fruit})
71  0.032232  frozenset({whipped/sour cream, whole milk})
72  0.056024              frozenset({yogurt, whole milk})

[73 rows x 2 columns]

In [18]:
rules_mlxtend = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules_mlxtend

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({soda}),frozenset({bottled water}),0.174377,0.110524,0.028978,0.166181,1.503577,1.0,0.009705,1.066750,0.405656,0.113230,0.062573,0.214185
1,frozenset({bottled water}),frozenset({soda}),0.110524,0.174377,0.028978,0.262190,1.503577,1.0,0.009705,1.119017,0.376535,0.113230,0.106359,0.214185
2,frozenset({bottled water}),frozenset({whole milk}),0.110524,0.255516,0.034367,0.310948,1.216940,1.0,0.006126,1.080446,0.200417,0.103617,0.074456,0.222724
3,frozenset({whole milk}),frozenset({bottled water}),0.255516,0.110524,0.034367,0.134501,1.216940,1.0,0.006126,1.027703,0.239450,0.103617,0.026956,0.222724
4,frozenset({other vegetables}),frozenset({citrus fruit}),0.193493,0.082766,0.028876,0.149238,1.803140,1.0,0.012862,1.078133,0.552273,0.116728,0.072470,0.249066
5,frozenset({citrus fruit}),frozenset({other vegetables}),0.082766,0.193493,0.028876,0.348894,1.803140,1.0,0.012862,1.238674,0.485603,0.116728,0.192685,0.249066
6,frozenset({whole milk}),frozenset({citrus fruit}),0.255516,0.082766,0.030503,0.119379,1.442377,1.0,0.009355,1.041577,0.411963,0.099108,0.039917,0.243965
7,frozenset({citrus fruit}),frozenset({whole milk}),0.082766,0.255516,0.030503,0.368550,1.442377,1.0,0.009355,1.179008,0.334375,0.099108,0.151829,0.243965
8,frozenset({domestic eggs}),frozenset({whole milk}),0.063447,0.255516,0.029995,0.472756,1.850203,1.0,0.013783,1.412030,0.490649,0.103800,0.291800,0.295073
9,frozenset({whole milk}),frozenset({domestic eggs}),0.255516,0.063447,0.029995,0.117390,1.850203,1.0,0.013783,1.061117,0.617231,0.103800,0.057597,0.295073
10,frozenset({rolls/buns}),frozenset({other vegetables}),0.183935,0.193493,0.042603,0.231620,1.197047,1.0,0.007013,1.049620,0.201713,0.127240,0.047274,0.225899
11,frozenset({other vegetables}),frozenset({rolls/buns}),0.193493,0.183935,0.042603,0.220179,1.197047,1.0,0.007013,1.046477,0.204103,0.127240,0.044413,0.225899
12,frozenset({other vegetables}),frozenset({root vegetables}),0.193493,0.108998,0.047382,0.244877,2.246605,1.0,0.026291,1.179941,0.688008,0.185731,0.152500,0.339789
13,frozenset({root vegetables}),frozenset({other vegetables}),0.108998,0.193493,0.047382,0.434701,2.246605,1.0,0.026291,1.426693,0.622764,0.185731,0.299078,0.339789
14,frozenset({other vegetables}),frozenset({tropical fruit}),0.193493,0.104931,0.035892,0.185497,1.767790,1.0,0.015589,1.098913,0.538522,0.136716,0.090010,0.263775
15,frozenset({tropical fruit}),frozenset({other vegetables}),0.104931,0.193493,0.035892,0.342054,1.767790,1.0,0.015589,1.225796,0.485239,0.136716,0.184204,0.263775
16,frozenset({whipped/sour cream}),frozenset({other vegetables}),0.071683,0.193493,0.028876,0.402837,2.081924,1.0,0.015006,1.350565,0.559803,0.122203,0.259569,0.276037
17,frozenset({other vegetables}),frozenset({whipped/sour cream}),0.193493,0.071683,0.028876,0.149238,2.081924,1.0,0.015006,1.091160,0.644352,0.122203,0.083544,0.276037
18,frozenset({other vegetables}),frozenset({whole milk}),0.193493,0.255516,0.074835,0.386758,1.513634,1.0,0.025394,1.214013,0.420750,0.200000,0.176286,0.339817
19,frozenset({whole milk}),frozenset({other vegetables}),0.255516,0.193493,0.074835,0.292877,1.513634,1.0,0.025394,1.140548,0.455803,0.200000,0.123228,0.339817
20,frozenset({yogurt}),frozenset({other vegetables}),0.139502,0.193493,0.043416,0.311224,1.608457,1.0,0.016424,1.170929,0.439613,0.149930,0.145977,0.267804
21,frozenset({other vegetables}),frozenset({yogurt}),0.193493,0.139502,0.043416,0.224383,1.608457,1.0,0.016424,1.109436,0.469042,0.149930,0.098641,0.267804
22,frozenset({whole milk}),frozenset({pastry}),0.255516,0.088968,0.033249,0.130123,1.462587,1.0,0.010516,1.047312,0.424831,0.106828,0.045174,0.251919
23,frozenset({pastry}),frozenset({whole milk}),0.088968,0.255516,0.033249,0.373714,1.462587,1.0,0.010516,1.188729,0.347166,0.106828,0.158765,0.251919
24,frozenset({pip fruit}),frozenset({whole milk}),0.075648,0.255516,0.030097,0.397849,1.557043,1.0,0.010767,1.236375,0.387036,0.099966,0.191184,0.257818
25,frozenset({whole milk}),frozenset({pip fruit}),0.255516,0.075648,0.030097,0.117788,1.557043,1.0,0.010767,1.047765,0.480544,0.099966,0.045588,0.257818
26,frozenset({rolls/buns}),frozenset({sausage}),0.183935,0.093950,0.030605,0.166390,1.771048,1.0,0.013324,1.086899,0.533490,0.123766,0.079952,0.246074
27,frozenset({sausage}),frozenset({rolls/buns}),0.093950,0.183935,0.030605,0.325758,1.771048,1.0,0.013324,1.210344,0.480506,0.123766,0.173788,0.246074
28,frozenset({soda}),frozenset({rolls/buns}),0.174377,0.183935,0.038332,0.219825,1.195124,1.0,0.006258,1.046003,0.197750,0.119797,0.043980,0.214114
29,frozenset({rolls/buns}),frozenset({soda}),0.183935,0.174377,0.038332,0.208402,1.195124,1.0,0.006258,1.042983,0.200066,0.119797,0.041212,0.214114
30,frozenset({rolls/buns}),frozenset({whole milk}),0.183935,0.255516,0.056634,0.307905,1.205032,1.0,0.009636,1.075696,0.208496,0.147942,0.070369,0.264776
31,frozenset({whole milk}),frozenset({rolls/buns}),0.255516,0.183935,0.056634,0.221647,1.205032,1.0,0.009636,1.048452,0.228543,0.147942,0.046213,0.264776
32,frozenset({rolls/buns}),frozenset({yogurt}),0.183935,0.139502,0.034367,0.186844,1.339363,1.0,0.008708,1.058220,0.310486,0.118888,0.055017,0.216600
33,frozenset({yogurt}),frozenset({rolls/buns}),0.139502,0.183935,0.034367,0.246356,1.339363,1.0,0.008708,1.082825,0.294453,0.118888,0.076490,0.216600
34,frozenset({whole milk}),frozenset({root vegetables}),0.255516,0.108998,0.048907,0.191405,1.756031,1.0,0.021056,1.101913,0.578298,0.154961,0.092487,0.320049
35,frozenset({root vegetables}),frozenset({whole milk}),0.108998,0.255516,0.048907,0.448694,1.756031,1.0,0.021056,1.350401,0.483202,0.154961,0.259479,0.320049
36,frozenset({sausage}),frozenset({whole milk}),0.093950,0.255516,0.029893,0.318182,1.245252,1.0,0.005887,1.091910,0.217372,0.093541,0.084173,0.217587
37,frozenset({whole milk}),frozenset({sausage}),0.255516,0.093950,0.029893,0.116992,1.245252,1.0,0.005887,1.026094,0.264545,0.093541,0.025431,0.217587
38,frozenset({whole milk}),frozenset({tropical fruit}),0.255516,0.104931,0.042298,0.165539,1.577595,1.0,0.015486,1.072631,0.491782,0.132950,0.067713,0.284320
39,frozenset({tropical fruit}),frozenset({whole milk}),0.104931,0.255516,0.042298,0.403101,1.577595,1.0,0.015486,1.247252,0.409045,0.132950,0.198238,0.284320
40,frozenset({yogurt}),frozenset({tropical fruit}),0.139502,0.104931,0.029283,0.209913,2.000475,1.0,0.014645,1.132873,0.581197,0.136106,0.117288,0.244491
41,frozenset({tropical fruit}),frozenset({yogurt}),0.104931,0.139502,0.029283,0.279070,2.000475,1.0,0.014645,1.193594,0.558749,0.136106,0.162194,0.244491
42,frozenset({whipped/sour cream}),frozenset({whole milk}),0.071683,0.255516,0.032232,0.449645,1.759754,1.0,0.013916,1.352735,0.465077,0.109273,0.260757,0.287895
43,frozenset({whole milk}),frozenset({whipped/sour cream}),0.255516,0.071683,0.032232,0.126144,1.759754,1.0,0.013916,1.062323,0.579917,0.109273,0.058667,0.287895
44,frozenset({yogurt}),frozenset({whole milk}),0.139502,0.255516,0.056024,0.401603,1.571735,1.0,0.020379,1.244132,0.422732,0.165267,0.196226,0.310432
45,frozenset({whole milk}),frozenset({yogurt}),0.255516,0.139502,0.056024,0.219260,1.571735,1.0,0.020379,1.102157,0.488608,0.165267,0.092688,0.310432

Given the data association analysis above, the presence of bottled beer does not imply the presence of rolls. Although both meet the minimum support of 0.028, the rule does not meet the minumum requirement for lift that has been set at 1. Although this correlation was not proven to be significant, the idea that the presence of cookouts may effect the market basket can still be applied. The data above contains other rules that may be applicable such as the correlation of sausage and rolls, soda and rolls. 


The data analytics department has been researching the correlation of cookout items frequenly purchased at the same time by customers. The original analysis was that the purchase of bottled beer would frequently lead to the puchase of buns/rolls, with the mindset that beer is a popular cookout beverage and buns are also often bought for cookouts to use with the meats. After further analysis, this association was not frequent enough to be supported. However, the team has discovered additional frequent associations that fall under the cookout category such as buns and sausage, buns and soda, and buns and vegetables. Our suggestion is to create a cookout category promotion that incentivies the customer to buy more items than they may have orginally. Items like buns, meat, cheese, chips, dip, beet, soda, etc. may all be included in the promotion, and if the customer buys 5 items say they get $2.50 off or some other percent off. We may also structure the promotion that the customer has to spend $30 to get $5 off. While this may not directly buy buns if they buy meat but if they are already planning on buying these two things, this may incentivise them to spend a little more than they would have to get a couple dollars off.